// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using _684BakOMeter.Web.Data.Persistence;

#nullable disable

namespace _684BakOMeter.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413215207_initCreate")]
    partial class initCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("_684BakOMeter.Web.Domain.Entities.ChugAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChugType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("OneVsOneMatchIdAsPlayer1")
                        .HasColumnType("integer");

                    b.Property<int?>("OneVsOneMatchIdAsPlayer2")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("ChugAttempts");
                });

            modelBuilder.Entity("_684BakOMeter.Web.Domain.Entities.OneVsOneMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChugType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("Player1AttemptId")
                        .HasColumnType("integer");

                    b.Property<int>("Player1Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Player2AttemptId")
                        .HasColumnType("integer");

                    b.Property<int>("Player2Id")
                        .HasColumnType("integer");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChugType");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Player1AttemptId")
                        .IsUnique();

                    b.HasIndex("Player2AttemptId")
                        .IsUnique();

                    b.HasIndex("Player2Id");

                    b.HasIndex("WinnerId");

                    b.HasIndex("Player1Id", "Player2Id");

                    b.ToTable("OneVsOneMatches");
                });

            modelBuilder.Entity("_684BakOMeter.Web.Domain.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("_684BakOMeter.Web.Domain.Entities.ChugAttempt", b =>
                {
                    b.HasOne("_684BakOMeter.Web.Domain.Entities.Player", "Player")
                        .WithMany("Attempts")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("_684BakOMeter.Web.Domain.Entities.OneVsOneMatch", b =>
                {
                    b.HasOne("_684BakOMeter.Web.Domain.Entities.ChugAttempt", "Player1Attempt")
                        .WithOne("OneVsOneMatchAsPlayer1")
                        .HasForeignKey("_684BakOMeter.Web.Domain.Entities.OneVsOneMatch", "Player1AttemptId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("_684BakOMeter.Web.Domain.Entities.Player", "Player1")
                        .WithMany("MatchesAsPlayer1")
                        .HasForeignKey("Player1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_684BakOMeter.Web.Domain.Entities.ChugAttempt", "Player2Attempt")
                        .WithOne("OneVsOneMatchAsPlayer2")
                        .HasForeignKey("_684BakOMeter.Web.Domain.Entities.OneVsOneMatch", "Player2AttemptId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("_684BakOMeter.Web.Domain.Entities.Player", "Player2")
                        .WithMany("MatchesAsPlayer2")
                        .HasForeignKey("Player2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_684BakOMeter.Web.Domain.Entities.Player", "Winner")
                        .WithMany("MatchesWon")
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Player1");

                    b.Navigation("Player1Attempt");

                    b.Navigation("Player2");

                    b.Navigation("Player2Attempt");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("_684BakOMeter.Web.Domain.Entities.ChugAttempt", b =>
                {
                    b.Navigation("OneVsOneMatchAsPlayer1");

                    b.Navigation("OneVsOneMatchAsPlayer2");
                });

            modelBuilder.Entity("_684BakOMeter.Web.Domain.Entities.Player", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("MatchesAsPlayer1");

                    b.Navigation("MatchesAsPlayer2");

                    b.Navigation("MatchesWon");
                });
#pragma warning restore 612, 618
        }
    }
}
